# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'Chatwoot'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO_DARK
  value: '/brand-assets/logo_thumbnail.svg'
- name: BRAND_URL
  value: 'https://theagentive.ai/'
- name: WIDGET_BRAND_URL
  value: 'https://theagentive.ai/'
- name: BRAND_NAME
  value: 'Chatwoot'
- name: TERMS_URL
  value: 'https://theagentive.ai/'
- name: PRIVACY_URL
  value: 'https://theagentive.ai/'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
